### ISSUE TITLE
Support for date time and currency formatting

### ISSUE THREAD

**Issue by rahuljain840** [lhz516/react-simple-i18n#5]
I am using this library in my project as it is small in size and completing my need. The only missing thing is support for number and datetime format. Can you give me insight on that, how can I achieve that. I will collaborate with you on that.

**Comment by lhz516** [comment]
Here's an example for currency :
```js
const langData = {
  enUS: {
    price: '$ %s%',
  },
  zhCN: {
    price: '%s% ¥',
  },
}
```
In the jsx:
```js
t('price', '100')
```

However, it's tricky to support date time. This library can support some simple cases, but for complicated ones, you may want to use some 3rd party date time library to do the i18n
